In [17]:
import pandas as pd
import numpy as np
import math

In [18]:
#Lectura de datos
columns = pd.read_csv('datos.csv')
Y = columns['promedio']
X1 = columns['edad']
X2 = columns['nmat']
X3 = columns['hestudio']
X4 = columns['recreo']
X5 = columns['amigos']

In [19]:
# Procesando las sumas
def sum_x_square(x):
    sum = 0
    for value in x:
        sum += pow(float(value),2)
    return sum

def sum_x1_x2(x1,x2):
    sum = 0
    for valueX1, valueX2 in zip(x1,x2):
        sum += float(valueX1) * float(valueX2)
    return sum

def sum_x_y(x,y):
    sum = 0
    for valueX, valueY in zip(x,y):
        sum += float(valueX) * math.pow(math.e, 1/float(valueY))
    return sum

In [28]:
#Matriz X
x1_square = sum_x_square(np.array(X1))
x1_times_x2 = sum_x1_x2(np.array(X1), np.array(X2))
x2_square = sum_x_square(np.array(X2))
print(x1_square)
print(x2_square)

16131.0
1288.0


In [29]:
#Matriz Y
y_times_x1 = sum_x_y(np.array(X1), np.array(Y))
y_times_x2 = sum_x_y(np.array(X2), np.array(Y))
print(y_times_x1)
print(y_times_x2)

780.7376422600148
220.755402657706


In [30]:
#Construyendo las matrices
x = np.matrix([[x1_square, x1_times_x2], [x1_times_x2, x2_square]])
y = np.matrix([[y_times_x1], [y_times_x2]])
print(x)
print(y)

[[16131.  4542.]
 [ 4542.  1288.]]
[[780.73764226]
 [220.75540266]]


In [31]:
#Matriz transpuesta
x_transp = x.T
print(x_transp)

[[16131.  4542.]
 [ 4542.  1288.]]


In [24]:
#Resolviendo
B = np.linalg.inv(x_transp * x) * (x_transp * y)
print(B)

[[0.01986231]
 [0.10135155]]


In [25]:
#Alphas
alpha1 = float(B[0]) 
alpha2 = float(B[1])  

In [26]:
#El modelo final
model = "y^(-1) = x1 * "+str(round(alpha1,5))+" + x2 * "+str(round(alpha2,5))+""
print(model)

y^(-1) = x1 * 0.01986 + x2 * 0.10135
